# These are supported funding model platforms

github: marcelklehr # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: floccus
liberapay: marcelklehr
custom: https://www.paypal.me/marcelklehr1
