kind: pipeline
name: default

steps:
  - name: test in chrome
    image: node
    environment:
      SAUCE_USERNAME: marcelklehr
      SAUCE_ACCESS_KEY:
        from_secret: SAUCE_ACCESS_KEY
      SELENIUM_BROWSER: chrome
    commands:
      - npm run keygen
      - npm run build-release
      - npm run test

  - name: test
    image: node
    environment:
      SAUCE_USERNAME: marcelklehr
      SAUCE_ACCESS_KEY:
        from_secret: SAUCE_ACCESS_KEY
      SELENIUM_BROWSER: firefox
    commands:
      - npm install
      - npm run keygen
      - npm run build-release
      - npm run test

services:
  - name: saucelabs
    image: joscha/docker-sauce-connect
    environment:
      SAUCE_USERNAME: 'marcelklehr'
      SAUCE_ACCESS_KEY:
        from_secret: SAUCE_ACCESS_KEY
    ports:
      - 8000
    commands:
      - sc -P 8000 -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY

  - name: nextcloud15
    image: 'nextcloud:15'
    ports:
      - 80
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
    commands:
      - apt update && apt install git -y
      - git clone --depth=1 --branch="v1.0.6" "https://github.com/nextcloud/bookmarks.git" "custom_apps/bookmarks"
      - wget https://getcomposer.org/installer -0 - -q | php -- --quiet
      - cd custom_apps/bookmarks && composer install
      - php occ app:enable "bookmarks"

  - name: nextcloud16
    image: 'nextcloud:16'
    ports:
      - 80
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
    commands:
      - apt update && apt install git -y
      - git clone --depth=1 --branch="master" "https://github.com/nextcloud/bookmarks.git" "custom_apps/bookmarks"
      - wget https://getcomposer.org/installer -0 - -q | php -- --quiet
      - cd custom_apps/bookmarks && composer install
      - php occ app:enable "bookmarks"
